// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-jwt
:page-layout: guide
:page-duration: 15 minutes
:page-releasedate: 2017-12-11
:page-description: Learn how to control user and role access to microservices using MicroProfile JWT.
:page-tags: ['JWT', 'MP-JWT', "MicroProfile"]
:page-permalink: /guides/{projectid}
:page-related-guides: ['cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Securing microservices with JSON Web Tokens (JWT)

Learn how to control user and role access to microservices using MicroProfile JWT.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to control user and role access to microservices using MicroProfile JWT. The great benefit from adding JWT security to your microservices is that it provides certain groups of users with access to specific functions.

One of the main strategies to propagate the security state from clients to services or even from services to services involves the use of security tokens. In fact, the main security protocols in use today are based on security tokens such as OAuth2, OpenID Connect, SAML, WS-Trust, WS-Federation and others. While some of these standards are more related with identity federation, they share a common concept regarding security tokens and token based authentication.
For RESTful based microservices, security tokens offer a very lightweight and interoperable way to propagate identities across different services.

You will add JWT authentication and authorization to the microservices provided: `SystemResource` and `InventoryResource` while a simple front end to handle the authentication is also provided.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished
JWT security implementation for the services in the application. Feel free to give it a try before you proceed with building your own.

To try out the application, first navigate to the `finish` directory and then execute the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn clean install liberty:start-server
```

Point your browser to the front-end web application endpoint: `http://localhost:9090/system.jsf`. From here you have the ability to log into the system using the form based login provided.
Log in with one of the following user information:

|===
| *Username* | *Password* | *Role*
| `bob` | `pwd` | `admin, user`
| `alice` | `alicepwd` | `user`
| `carl` | `carlpwd` | `user`
|===

You should now be redirected to a another page that will display the logged in user, the current OS of your localhost and the web token that is being used by the front-end to access the data.
In addition, if you are logged in as an `admin` user, you will see the inventory size being `0`; if you are logged in as an normal `user`, your will see `-1` instead (which means you are forbidden from accessing the inventory size data in the back end).

Once you are done checking out the application, stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.
Proceed with the following two sections to add MicroProfile JWT to the back-end and basic app security to the front-end.

// =================================================================================================
// Adding Microprofile-JWT to backend services
// =================================================================================================

== Adding Microprofile-JWT to backend services

The MicroProfile JWT feature is added as a dependency in your `pom.xml` file. This feature allows you to
use the MicroProfile JWT API to inject user authorization information in the RESTful services.

// =================================================================================================
// Adding the JWT Resource class
// =================================================================================================

=== Adding the JWT Resource class

Create a `/start/backendServices/src/main/java/io/openliberty/guides/inventory/JwtResource.java` file to enable a service that retrieves information about the given Json Web Token.

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/inventory/JwtResource.java[tags=jwt;!copyright;!doc]
----

// the two sentences below are incorrect: the JsonWebToken does not create JSON Web Token, @RequestScoped has nothing to do with JWT, please check CDI gudie for more info about annotation
// The `org.eclipse.microprofile.jwt,JsonWebToken` contains the classes required to create and use the JSON Web Token.
//
// The `@RequestScoped` annotation is required because the JWT service needs to only be activated when a login request is made.

Let's break down the annotations:

- `@Path("jwt")` is used to state the REST request path to access this class which in this case is JWT.
- `@GET` indicates that the method serves all GET HTTP requests at its endpoint.

Role names used in `@RolesAllowed` have been mapped to group names in the MP-JWT "groups" claim, which results in an allowing authorization decision wherever the security constraint has been applied.

Let's break down the methods:

- `getJwtUserName()` retrieves the user name from the injected `JsonWebToken jwtPrincipal`.
- `getGroups()` gets the user groups information from the Json Web Token from the SecurityContext.
`SecurityContext.getUserPrincipal()` returns an object in type `java.security.Principal`, this object is also an instance of `org.eclipse.microprofile.jwt.JsonWebToken`.
- `getCustomClaim()` gets the custom claim from the provided Json Web Token if the authenticated user has the role of `admin`. Otherwise, it returns `Status.FORBIDDEN`.
`SecurityContext.isUserInRole(String)` returns true for any name that is included in the MP-JWT "groups" claim, as well as for any role name that has been mapped to a group name in the MP-JWT "groups" claim.

// =================================================================================================
// Add the InventoryResource class
// =================================================================================================

=== Add the InventoryResource class

Create the class `InventoryResource.java` in `/start/backendServices/src/main/java/io/openliberty/guides/inventory/` to add code to return the JWT token with all HTTP requests.

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=jwt;!copyright;!doc]
----

The `@RolesAllowed({"admin", "user"})` annotation sets what roles are allowed to access the service, which in this case is `admin` or `user`.

The `authHeader` retrieves the authorization header from the GET request.

The final addition of code `return Response.ok(manager.get(props)).build();` adds the authentication header to the client that will send HTTP GET request to the other service.

// =================================================================================================
// Add the SystemClient class
// =================================================================================================

=== Add the SecuredSystemClient class

Add the `SecuredSystemClient` class in `/start/backendServices/src/main/java/io/openliberty/guides/inventory/client/SecuredSystemClient.java` file.

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/inventory/client/SecuredSystemClient.java[tags=jwt;!copyright;!doc]
----

The `SecuredSystemClient` class inherits methods from the `SystemClient` class in terms of sending HTTP GET request to the system service to retrieve system properties.
However, it overrides the `buildClientBuilder()` method by adding the authorization header to the returned builder: `return builder.header(HttpHeaders.AUTHORIZATION, authHeader)`.
By adding the authorization header to the client request, the `SecuredSystemClient` can access services that are secured.


// =================================================================================================
// Add the SystemResource class
// =================================================================================================

=== Add the SystemResource class

Add the `SystemResource.java` class in `finish/backendServices/src/main/java/io/openliberty/guides/system/SystemResource.java`.

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/system/SystemResource.java[tags=jwt;!copyright;!doc]
----

The `@RolesAllowed({"admin", "user"})` annotation allows only authenticated users with "admin" and "user" roles to access the `system` service.
Therefore, this service is properly secured.

// =================================================================================================
// Adding JWT builder and form-based login to the front-End
// =================================================================================================

== Adding JWT builder and form-based login to the front-End

A very simple front-end web application is provided to allow you to log into the application with pre-defined users that have different roles such as `admin` and `user`


// =================================================================================================
// The User Object
// =================================================================================================

=== The User Object

A `User` class has been provided for you in `/start/frontendUI/src/main/java/io/openliberty/guides/ui/User.java`.

This is a user model that contains information regarding a user. It has `get` and `set` methods for the username, password and role.

// =================================================================================================
// Creating the login bean
// =================================================================================================

=== Creating the login bean

Create a class `LoginBean.java` in `/start/frontendUI/src/main/java/io/openliberty/guides/ui/` to handle log in requests to the back-end and create the JWT token required for authentication.

[source, java, indent=0]
----
include::finish/frontendUI/src/main/java/io/openliberty/guides/ui/LoginBean.java[tags=jwt;!copyright;!doc]
----

Let's break down the methods:

- `doLogIn()` authenticates users who are pre-defined in the front-end `server.xml` file and creates a user object and a JWT token. It will then create an http session used for continued access to the application.
- `buildJWT()` creates a JWT token with provide user information.
- `getRole()` returns the role for a user which is either `admin` or `user`.

// =================================================================================================
// Creating the system bean
// =================================================================================================

=== Creating the system bean

Create a class `SystemBean.java` in `/start/frontendUI/src/main/java/io/openliberty/guides/ui` to get information about the currently logged in user.

[source, java, indent=0]
----
include::finish/frontendUI/src/main/java/io/openliberty/guides/ui/SystemBean.java[tags=jwt;!copyright;!doc]
----

Let's break down the methods:

- `getOs()` returns a String of the operating system for a session from the back-end by doing a GET request with the auth header containing the JSON Web Token.
- `getInvSize()` returns the size of the inventory list for a given user from the session.
- `getJwt()` returns the JSON Web Token for the current session.
- `getUserName()` returns the username of the user currently logged in from the session.
- `getUserRole()` returns the role of the currently logged in user.

// =================================================================================================
// Creating the Server configuration file
// =================================================================================================

=== Creating the Server Configuration File

Create a config file named `server.xml` in `/start/frontendUI/src/main/liberty/config` to pre-define users with their names, passwords and roles.

[source, java, indent=0]
----
include::finish/frontendUI/src/main/liberty/config/server.xml[tags=jwt;!copyright;!doc]
----

The `<feature>jwt-1.0</feature>` adds the libraries required for JWT builder implementation.

The `<basicRegistry id="basic" realm="WebRealm">` section adds users and roles to a basic registry so that they can be stored on the server rather than a database.
User names and passwords are defined here, as well as user groups, and will be used for front-end authentication.

The `<application>` section sets the application location, it's type so in this case a `.war` file. It maps user groups with user security roles, which defines user accessibility for certain endpoints in this application.

The `<jwtBuilder>` section is required in order to build a JWT for an authenticated user and sets the tokens expiration time to 24 hours.

// =================================================================================================
// Building and running the application
// =================================================================================================

// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

When the open Liberty application server has started you can log into the system using the simple front-end that has been provided. Use one of the following credentials below to log in:

|===
| *Username* | *Password* | *Role*
| `bob` | `pwd` | `admin, user`
| `alice` | `alicepwd` | `user`
| `carl` | `carlpwd` | `user`
|===

Below is the endpoint used to log into the system:

* `http://localhost:9090/system.jsf`

Once logged in you will be able to see some basic information about your currently logged in session. The Username of the logged in user, your role which will be admin,
the current operating system, the size of your inventory and the JSON Web Token (JWT) that is being used for authorization in the back end.
Please remember that if you log in with a user without the role of admin you will be unable to see the inventory size as you will not have the correct permissions.

include::{common-includes}/mvnpackage.adoc[]
// =================================================================================================
// Testing MP-JWT authorization
// =================================================================================================

== Testing MP-JWT authorization

You will write two test classes `EndpointWithJwtTest` and `JwtTest` to
validate the state of each service.

Begin by creating a `start/backendServices/src/test/java/it/io/openliberty/guides/jwt/EndpointWithJwtTest.java` file:

[source, java, indent=0]
----
include::finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/EndpointWithJwtTest.java[tags=test]
----

In the `setup()` before test cases, an authorization header is created with the credential of a test user who has the name as `TESTUSER` and role as `admin`.
Then, this authorization header is added when the test client tries to send a `get` request to a secured service to retrieve any information.

Each test case tries to first assert that with a valid authorization header, it can can get a `Status.OK` code from the response.
If the response returns a `Status.FORBIDDEN` code, which means the authorization header is invalid, the test will fail.

After assuring the response code is correct, each test tries to get the content from the designated endpoint and compares the result with its expected value.

Then, create a `start/backendServices/src/test/java/it/io/openliberty/guides/jwt/JwtTest.java` file:

[source, java, indent=0]
----
include::finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/JwtTest.java[tags=test]
----

Similarly, in the `setup()` step of the `JwtTest`, an authorization header is created with the credential of a test user who has the name as `TESTUSER` and role as `user`.
Then, this authorization header is added when the test client tries to send a `get` request to a secured JWT service.

* `testJWTGetName()` tries to access the `https://localhost:5051/inventory/jwt/username` endpoint to get the username from the JWT token, and verify
if the username is same as `TESTUSER`.

* `testJWTGetCustomClaim()` tries to access the `https://localhost:5051/inventory/jwt/customClaim` endpoint. Since this service is secured, and only accessible for users who have the `admin` role,
the test is asserting that the current test user who has a normal `user` role is forbidden from accessing it.

include::{common-includes}/mvnverify.adoc[]

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.jwt.EndpointWithJwtTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.444 sec - in it.io.openliberty.guides.jwt.EndpointWithJwtTest
Running it.io.openliberty.guides.jwt.JwtTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.086 sec - in it.io.openliberty.guides.jwt.JwtTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have learned how to add MP-JWT authentication to your microservices so that they are now secure. Then you wrote tests to validate that.

Feel free to try one of the related MicroProfile guides. They demonstrate new technologies that you can learn and expand on top what you built here.

include::{common-includes}/finish.adoc[]
