// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-jwt
:page-layout: guide
:page-duration: 15 minutes
:page-releasedate: 2017-12-11
:page-description: Learn how to control user and role access to microservices using MicroProfile JWT.
:page-tags: ['JWT', 'MP-JWT']
:page-permalink: /guides/{projectid}
:page-related-guides: ['cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify

= Adding security using java web tokens (JWT) to your microservices

Learn how to control user and role access to microservices using MicroProfile JWT.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to control user and role access to microservices using MicroProfile JWT. The great benefit from adding JWT security to your microservices allows you to allow certain groups of users access to specific functions.

One of the main strategies to propagate the security state from clients to services or even from services to services involves the use of security tokens. In fact, the main security protocols in use today are based on security tokens such as OAuth2, OpenID Connect, SAML, WS-Trust, WS-Federation and others. While some of these standards are more related with identity federation, they share a common concept regarding security tokens and token based authentication.
For RESTful based microservices, security tokens offer a very lightweight and interoperable way to propagate identities across different services.

You will add JWT security and authentication to the microservices provided: `PropertiesResource` and `InventoryResource` while we provide you with a simple front end to handle the authentification.
If you want to learn how to create a RESTful application, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].

// =================================================================================================
// Getting Started
// =================================================================================================

// include::{common-includes}/gitclone.adoc[]

== Getting started

The fastest way to work through this guide is to clone the git repository and use the starting project
that is provided in the `start` directory. To do this, run the following commands:

[subs="attributes"]
----
git clone https://github.com/openliberty/guide-mp-jwt.git
cd guide-mp-jwt/start
----

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished
JWT security implementation for the services in the application. Feel free to give it a try before you proceed with building your own.

To try out the application, first navigate to the `finish` directory and then execute the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn clean install
mvn liberty:start-server

```

Point your browser to Front-end web application endpoint: `http://localhost:9090/system.jsf`. From here you have the ability to log into the system using the form based login provided. Use the admin username and password `Username: bob` `Password: pwd` then click the log in button. You should now be redirected to a another page with that will display the logged in User, the current OS of that user and the web token that is being used by the front-end to access the data.

Once you are done checking out the application, stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Adding JWT authentication to the inventory application
// =================================================================================================

== Adding JWT authentication to inventory application

Begin by enabling the MicroProfile JWT feature in your `pom.xml` file. This feature allows you to
use the MicroProfile JWT API to provide token based authentication to your RESTful services.

Navigate to the start/pom.xml file and add the required dependency:

[source, xml, indent=0]
```
            <dependency>
                <groupId>org.eclipse.microprofile.jwt</groupId>
                <artifactId>microprofile-jwt-auth-api</artifactId>
                <version>${version.microprofile.api.jwt}</version>
                <scope>provided</scope>
            </dependency>
```

Proceed with the two sections below to add JWT authentication to the back-end and
front-end services.

// =================================================================================================
// Adding the JWT Resource class
// =================================================================================================

=== Adding the JWT Resource class

Create `JwtResource.java` class in `/start/backendServices/src/main/java/io/openliberty/guides/inventory/` to privide information about a given JWT token.

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/inventory/JwtResource.java[tags=!copyright;!doc]
----

The `org.eclipse.microprofile.jwt,JsonWebToken` contians the classes required to create and use the Java Web Token.

The `@RequestScoped` annotation is required because the JWT service needs to only be activated when a login request is made.

The `@Path("jwt")` annotation is used to state the REST request path to access this class which in this case is jwt.

The `@GET` annotation states that it is a HTTP GET request that will be used to access a method.

The `getJwtUserName()` method gets the user name from the provided toekn.

The `getGroups(@Context SecurityContext securityContext)` method gets the groups defined for access to the backend system from the provided SecurityContext. These groups are defined in the server.xml file located in the front-end auth service `finish/frontendUI/src/main/liberty/config/server.xml`

The `getStatus(@Context SecurityContext securityContext)` method is used to get the status of the machine from the provided SecurityContext if the request is in the group admin.

// =================================================================================================
// Add the InventoryResource class
// =================================================================================================

=== Add the InventoryResource class

Create the class `InventoryResource.java` in `/start/backendServices/src/main/java/io/openliberty/guides/inventory/` to add code to return the JWT token with all HTTP requests.

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=!copyright;!doc]
----

The `import javax.annotation.security.DenyAll;`
, `import javax.annotation.security.RolesAllowed;` imports contain the classes required to hande access to the code from different roles.

The `@RolesAllowed({"admin", "user"})` annotation sets what roles are allowed to access the class/method which in this case is `admin` or `user`.

The following code `String authHeader = httpHeaders.getRequestHeaders().getFirst(HttpHeaders.AUTHORIZATION);` takes the auth header from the GET request and puts it into a string.

The final addition of code is `return Response.ok(manager.get(hostname, authHeader), MediaType.APPLICATION_JSON).build();` that adds the authHeader String created above to the HTTP GET response.

// =================================================================================================
// Add the SystemClient class
// =================================================================================================

=== Add the SystemClient class

Add the class `SystemClient.java` in `/start/backendServices/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java` to add code to return the auth header in the GET requests.

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[tags=!copyright;!doc]
----

Not sure why required changes have been made... Need to talk to developer!

// =================================================================================================
// Add the SystemResource class
// =================================================================================================

=== Add the SystemResource class

Add the `SystemResource.java` class in `finish/backendServices/src/main/java/io/openliberty/guides/system/SystemResource.java` to add code to return the auth header in the GET requests.

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/system/SystemResource.java[tags=!copyright;!doc]
----

The `import javax.annotation.security.RolesAllowed;` import allows roles access to methods.

Add the `@RolesAllowed({"admin", "user"})` code to allow certain roles to access the metod.

// =================================================================================================
// Adding JWT token creation and login Service to the Front-End
// =================================================================================================

== Adding JWT token creation and login Service to the Front-End

We have provided you with a very simple front-end web application to allow you to log into the back-end system with pre defined users that have different roles such as `admin` and `user` located in `finish/frontendUI/src/main/java/io/openliberty/guides/ui`


// =================================================================================================
// The User Object
// =================================================================================================

=== The User Object

Open the class `User.java` in `/start/frontendUI/src/main/java/io/openliberty/guides/ui/` this is a user object that can be used to authenticate against the back end.

[source, java, indent=0]
----
include::finish/frontendUI/src/main/java/io/openliberty/guides/ui/User.java[tags=!copyright;!doc]
----

This is just a simple Java object that contains information regarding a user. It has `get` and `set` methods for the username, password and role.

// =================================================================================================
// Creating the login bean
// =================================================================================================

=== Creating the login bean

Create a class `LoginBean.java` in `/start/frontendUI/src/main/java/io/openliberty/guides/ui/` to handle log in requests to the back-end and create the JWT token required for authentication.

[source, java, indent=0]
----
include::finish/frontendUI/src/main/java/io/openliberty/guides/ui/LoginBean.java[tags=!copyright;!doc]
----

The `com.ibm.websphere.security.jwt.\*;` import contains the required classes to create the JWT token.

The `doLogIn()` method logs into the back end system by creating a user object and a JWT token. It will then create a http session used for continued access to the back end system.

The `buildJWT(String userName, String role)` method is used to create a JWT token for a given user.

The `getRole(HttpServletRequest request)` method returns the role for a user which is either `admin` or `user`.

// =================================================================================================
// Creating the system bean
// =================================================================================================

=== Creating the system bean

Create a class `SystemBean.java` in `/start/frontendUI/src/main/java/io/openliberty/guides/ui` to get information about the currently logged in user.

[source, java, indent=0]
----
include::finish/frontendUI/src/main/java/io/openliberty/guides/ui/SystemBean.java[tags=!copyright;!doc]
----

The `getOs()` method returns a String of the operating system for the session from the back-end by doing a GET request with the auth header containing the Java web token.

The `getInvSize()` method returns the size of the inventory list for a given user from the session.

The `getJwt()` method returns the Java web token for the current session.

The `getUserName()` method returns the username of the user currently logged in from the session.

The `getUserRole()` metho returns the role of the currently logged in user.

// =================================================================================================
// Creating the Server configuration file
// =================================================================================================

=== Creating the Server Configuration File

Create a class `server.xml` in `/start/frontendUI/src/main/liberty/config` to get information about the currently logged in user.

[source, java, indent=0]
----
include::finish/frontendUI/src/main/liberty/config/server.xml[tags=!copyright;!doc]
----

The `<feature>jwt-1.0</feature>` adds the libaries required for JWT implementation.

The `<basicRegistry id="basic" realm="WebRealm">` section adds users and roles to a basic registry so that they can be stored the server rather than a database.

The `<application>` section sets the applicaiton location, it's type so in this case a `.war` file, it's name and the roles allowed to access it.

The `<jwtBuilder>` section is required in order to build a JWT for an authenticated user and sets the tokens expiary time to 24 hours.

// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

To build the application use the following maven command:

`mvn clean install`

Once the above build is succesfull use the following command to run the server:

`mvn liberty:start-server`

When the open Liberty application server has started you can log into the system using the simple front-end that has been provided. Use the credentials below to log in:

Username: `bob`
Password: `pwd`

* `http://localhost:9090/system.jsf`

Once logged in you will be able to see some basic information about your currently logged in session. The Username of the logged in user, your role which will be admin,
the current operating system, the size of your inventory and the java web token (JWT) that is being used for authentication to the back end.


// =================================================================================================
// Testing JWT Authentication
// =================================================================================================

== Testing JWT Authentication

You will write two test classes `EndpointWithJwtTest` and `JwtTest` to
validate the state of each service.

Begin by creating a `start/backendServices/src/test/java/it/io/openliberty/guides/jwt/EndpointWithJwtTest.java` file:

[source, java, indent=0]
----
include::finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/EndpointWithJwtTest.java[tags=test]
----

In the `setup()` before test cases, an authorization header is created with the credential of a test user who has the name as `TESTUSER` and role as `admin`.
Then, this authorization header is added when the test client tries to send a `get` request to a secured service to retrieve any information.

Each test case tries to first assert that, with a valid authorization header, it can can get a `Status.OK` code from the response.
If the response returns a `Status.FORBIDDEN` code, which means the authorization header is invalid, the test will fail.

After assuring the response code is correct, each test tries to get the content from the designated endpoint and compares the result with its expected value.

Then, create a `start/backendServices/src/test/java/it/io/openliberty/guides/jwt/JwtTest.java` file:

[source, java, indent=0]
----
include::finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/JwtTest.java[tags=test]
----

Similarly, in the `setup()` step of the `JwtTest`, an authorization header is created with the credential of a test user who has the name as `TESTUSER` and role as `user`.
Then, this authorization header is added when the test client tries to send a `get` request to a secured JWT service.

The `testJWTGetName()` tries to access the `https://localhost:5051/inventory/jwt/username` endpoint to get the username from the JWT token, and verify
if the username is same as `TESTUSER`.

The `testJWTGetCustomClaim()` tries to access the `https://localhost:5051/inventory/jwt/customClaim` endpoint. Since this service is secured, and only accessible for users who have the `admin` role,
the test is asserting that the current test user who has a normal `user` role is forbidden from accessing it.

include::{common-includes}/mvnverify.adoc[]

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.jwt.EndpointWithJwtTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.444 sec - in it.io.openliberty.guides.jwt.EndpointWithJwtTest
Running it.io.openliberty.guides.jwt.JwtTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.086 sec - in it.io.openliberty.guides.jwt.JwtTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have learned how to add JWT Authentication to your microservices so that they are now secure.Then you wrote tests to validate that.

include::{common-includes}/finish.adoc[]
