// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-jwt
:page-layout: guide
:page-duration: 25 minutes
:page-releasedate: 2017-12-11
:page-description: Learn how to control user and role access to microservices using MicroProfile JWT.
:page-tags: ['JWT', 'MP-JWT', "JSON Web Tokens", "MicroProfile", "microservices"]
:page-permalink: /guides/{projectid}
:page-related-guides: ['cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Securing microservices with JSON Web Tokens (JWT)

Learn how to control user and role access to microservices with MicroProfile JWT.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to control user and role access to microservices with MicroProfile JWT. You will use Token Based Authentication mechanism to authenticate, authorize and verify user identities based on a security token.

You will add MP-JWT to validate security tokens in the `System` and `Inventory` microservices. In addition, you will add a simple front end to handle user login and logout.

// =================================================================================================
// Getting Started
// =================================================================================================

To begin, run the following commands, which clone the Git repository and access the starting project
that is provided in the `start` directory:

[subs="attributes"]
----
git clone https://github.com/OpenLiberty/draft-guide-microprofile-jwt.git
cd draft-guide-microprofile-jwt/start
----

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory contains the finished
JWT security implementation for the services in the application. Feel free to try the finished application before you proceed with building your own.

To try out the application, first navigate to the `finish` directory. Next, execute the following
Maven goals to build the application and run it inside of Open Liberty:

```
mvn clean install liberty:start-server
```

Point your browser to the front-end web application endpoint: `http://localhost:9090/system.jsf`. From here, you can log in to the system with the form-based login provided.
Log in with one of the following user information examples:

|===
| *Username* | *Password* | *Role*
| `bob` | `pwd` | `admin, user`
| `alice` | `alicepwd` | `user`
| `carl` | `carlpwd` | `user`
|===

You are redirected to a another page that displays the user who is logged in, the current OS of your localhost, and the security token that the front end uses when sending the HTTP request to access the data from the back end.
In addition, if you log in as an `admin` user, the current inventory size should appear. If you log in as a normal `user`, you see the message `You are not authorized to access the inventory service.` instead, which means you cannot access the inventory size data in the back end.

When you are done with the application, stop the server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Securing back-end services with MicroProfile JWT
// =================================================================================================

== Securing back-end services with MicroProfile JWT

The MicroProfile JWT feature (`microprofile-jwt-auth-api`) is added as a dependency in your `start/backendServices/pom.xml` file.

// =================================================================================================
// Creating the server configuration file
// =================================================================================================

=== Creating the server configuration file

Create a config file named `server.xml` in the `start/backendServices/src/main/liberty/config` directory.

[source, java, indent=0]
----
include::finish/backendServices/src/main/liberty/config/server.xml[tags=jwt]
----

The `<feature>mpJwt-1.0</feature>` feature adds the libraries that are required for MicroProfile JWT implementation.

The `<mpJwt>` element is required to configure the injection of the caller's JSON Web Tokens.

The `issuer` is responsible for issuing security tokens, enter a value for this attribute that matches the `iss` claim in the Java Web Token (JWT).

The `audiences` identifies the recipients that the JWT is intended for, it should match the value of the `aud` claim in the JWT.

The `keyName` attribute is required when you add the JWT signature validation key into the truststore file in the Secure Sockets Layer (SSL) configuration.
// =================================================================================================
// Securing the system service
// =================================================================================================

=== Securing the system service

Open the `start/backendServices/src/main/java/io/openliberty/guides/system/SystemResource.java` file and modify it to the following code:

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/system/SystemResource.java[tags=jwt;!copyright]
----

Role names used in `@RolesAllowed` are mapped to group names in the `groups` claim of the JSON Web Token, which results in an authorization decision wherever the security constraint is applied.

The `@RolesAllowed({"admin", "user"})` annotation allows only authenticated users with `admin` and `user` roles to access the `system` service.
Therefore, this service is properly secured.

// =================================================================================================
// Securing the inventory service
// =================================================================================================

=== Securing the inventory service

Open the `InventoryResource.java` file in the `start/backendServices/src/main/java/io/openliberty/guides/inventory/` directory and add roles-based access control as the following:

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=jwt;!copyright]
----

Similarly, for each specific service, the `@RolesAllowed` annotation sets which roles are allowed to access it. Therefore the inventory service is properly secured as well.

In addition, the `getPropertiesForHost()` method tries to get the HTTP Authorization header, which contains the corresponding security token, from the HTTP request caller, and use this authorization header to retrieve information from the `system` service.

The final addition of code `manager.get(hostname, authHeader)` adds the authentication header to the client that sends the HTTP GET request to the `system` service.

// =================================================================================================
// Add the SystemClient class
// =================================================================================================

=== Add the SecureSystemClient class

Add the `SecureSystemClient` class in the `start/backendServices/src/main/java/io/openliberty/guides/inventory/client/SecureSystemClient.java` file.

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/inventory/client/SecureSystemClient.java[tags=jwt;!copyright]
----

The `SecureSystemClient` class inherits methods, which handle the HTTP GET request to the system service to retrieve system properties, from the `SystemClient` class.
However, the class overrides the `buildClientBuilder()` method by adding the authorization header to the returned builder, `return builder.header(HttpHeaders.AUTHORIZATION, authHeader)`.
By adding the authorization header to the client request, the `SecureSystemClient` class can access services that are secured.

// =================================================================================================
// Adding the JwtResource class
// =================================================================================================

=== Adding the JwtResource class

Create a `start/backendServices/src/main/java/io/openliberty/guides/inventory/JwtResource.java` file to enable a service that retrieves information about the Json Web Token.

[source, java, indent=0]
----
include::finish/backendServices/src/main/java/io/openliberty/guides/inventory/JwtResource.java[tags=jwt;!copyright]
----

- `getJwtUsername()` retrieves the user name from the injected `JsonWebToken jwtPrincipal` type.
- `getGroups()` retrieves the user groups information from the Json Web Token from the SecurityContext.
`SecurityContext.getUserPrincipal()` returns an object in the `java.security.Principal` type. This object is also an instance of `org.eclipse.microprofile.jwt.JsonWebToken`.
- `getCustomClaim()` retrieves the custom claim from the Json Web Token if the authenticated user has the `admin` role. Otherwise, it returns a `Status.FORBIDDEN` message.
- `SecurityContext.isUserInRole(String)` returns `true` for any name that is included in the MP-JWT "groups" claim and for any role name that is mapped to a group name in the MP-JWT "groups" claim.

// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

When the Open Liberty application server has started, you can log in to the system with the simple front end that is provided. Use one of the following credentials to log in:

|===
| *Username* | *Password* | *Role*
| `bob` | `pwd` | `admin, user`
| `alice` | `alicepwd` | `user`
| `carl` | `carlpwd` | `user`
|===

The following endpoint is used to log in to the system:

* `http://localhost:9090/system.jsf`

Once you log in, you can see some basic information about your current session, including the user name of the user who is currently logged in, your role, which is admin, the current operating system, the size of your inventory, and the JSON Web Token (JWT) that is  used for authorization in the back end.
Remember that if you log in as a user without the role of admin, you will be unable to see the inventory size because you do not have the correct permissions.

include::{common-includes}/mvnpackage.adoc[]

// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

You will write `SystemEndpointTest`, `InventoryEndpointTest` and `JwtTest` classes to test the accessibility of different services.

To begin, create a `start/backendServices/src/test/java/it/io/openliberty/guides/jwt/SystemEndpointTest.java` file:

[source, java, indent=0]
----
include::finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/SystemEndpointTest.java[tags=test]
----

Then, create a `start/backendServices/src/test/java/it/io/openliberty/guides/jwt/InventoryEndpointTest.java` file:

[source, java, indent=0]
----
include::finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/InventoryEndpointTest.java[tags=test]
----

In the `setup()` before test cases, an authorization header is created with the credential of a test user who has the name `TESTUSER` and `admin` role.
Then, this authorization header is added when the test client tries to send a `get` request to a secure service to retrieve any information.

Each test case tries to first assert that with a valid authorization header, it can can get a `Status.OK` code from the response.
If the response returns a `Status.FORBIDDEN` code, which means the authorization header is invalid, the test fails.

After assuring the response code is correct, each test tries to get the content from the designated endpoint and compares the result with its expected value.

Next, create a `start/backendServices/src/test/java/it/io/openliberty/guides/jwt/JwtTest.java` file:

[source, java, indent=0]
----
include::finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/JwtTest.java[tags=test]
----

Similarly, in the `setup()` step of the `JwtTest`, an authorization header is created with the credential of a test user who has the name as `TESTUSER` and the `user` role.
The authorization header is added when the test client tries to send a `get` request to a secure JWT service.

* `testJWTGetName()` tries to access the `https://localhost:5051/inventory/jwt/username` endpoint to get the username from the JWT token, and verify
if the username is same as `TESTUSER`.

* `testJWTGetCustomClaim()` tries to access the `https://localhost:5051/inventory/jwt/customClaim` endpoint. Since this service is secured and only accessible for users who have the `admin` role,
the test is asserting that the current test user who has a normal `user` role is forbidden from accessing it.

include::{common-includes}/mvnverify.adoc[]

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.jwt.EndpointWithJwtTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.444 sec - in it.io.openliberty.guides.jwt.EndpointWithJwtTest
Running it.io.openliberty.guides.jwt.JwtTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.086 sec - in it.io.openliberty.guides.jwt.JwtTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have learned how to use MP-JWT to validate JWT and authorize users to secure your microservices.

Next, you can try one of the related MicroProfile guides. They demonstrate new technologies that you can learn and expand on what you built here.


// include::{common-includes}/finish.adoc[]

== Contribute to this guide

Is something missing or broken? Raise an https://github.com/OpenLiberty/draft-guide-microprofile-jwt/issues[issue],
or send us a https://github.com/OpenLiberty/draft-guide-microprofile-jwt/pulls[pull request].

https://github.com/OpenLiberty/draft-guide-microprofile-jwt[View this guide on github].
