// Copyright (c) 2018, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-jwt
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2018-03-09
:page-guide-category: microprofile
:page-essential: false
:page-description: Learn how to control user and role access to microservices using MicroProfile JWT.
:page-tags: ["MicroProfile", "Security"]
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Securing Java microservices with Eclipse MicroProfile JSON Web Token (MicroProfile JWT)
:page-seo-description: A getting started tutorial and an example on how to secure Java microservices to authenticate users and authorize access by validating JSON Web Tokens (JWT) using Eclipse MicroProfile JWT.
:guide-author: Open Liberty
= Securing microservices with JSON Web Tokens

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

You'll explore how to control user and role access to microservices with MicroProfile JSON Web Token (MicroProfile JWT).

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You will add MicroProfile JWT to validate security tokens in the `system` and
`inventory` microservices. You will use a token-based authentication mechanism
to authenticate, authorize, and verify user identities based on a security
token.

For microservices, a token-based authentication mechanism offers a lightweight
way for security controls and security tokens to propagate user identities
across different services. JSON Web Token (JWT) is becoming the most common
token format because it follows well-defined and known standards.

MicroProfile JWT standards define the required format of JWT for authentication
and authorization. The standards also map JWT token claims to various Java EE
container APIs and make the set of claims available through getters.


You will be working with two services, a frontend service and a secure, backend `system`
service. The frontend service logs a user in, and makes authorized requests to
the secure `system` service for JVM system properties using JWTs.

// =================================================================================================
//  JSON Web Tokens for authorization and authentication
// =================================================================================================

== JSON Web Tokens for authorization and authentication

A JSON Web Token is a self contained token designed to securely transmit information as a JSON object.
The information in this JSON object is digitally signed and can be trusted and verified by the recipient. 

A JWT contains 3 different parts, a header, a payload, and a signature, with each
part being seperated by a dot (`.`). An encoded token takes the following form:

`xxxxx.yyyyy.zzzzz`

The header contains the type of token, and the signing algorithm used.

The payload contains the claims of a token. The claims are statements about the
user and other information. Some examples of claims are `iss` (issuer), `exp`
(expiration time), and `groups` (the groups or roles of the user). Custom claims can be added to the token to include any other
information you would like to transmit.

The signature is used to verify that the message wasn't changed along the way, and
can verify that the sender of the JWT is who it says it is.

In our case, we will be using JWTs to authenticate a user, allowing them to make
authorized requests to the backend `system` service. 

The user will sign into the frontend application using a username and password,
at which point a JWT will be created by the frontend and signed using a private
key. The frontend will then make requests to the backend `system` service with the JWT
included in the `Authorization` header of the requests. The `system` service,
which is secured, will examine the JWT included with the request and use the
frontends public key to verify the signature of the JWT. This ensures that the
request did in fact come from the authorized frontend. After a JWT has been
validated, the information in the claims of the JWT, such as the user's role,
can be trusted and will be used to determine which system properties the user
has access to in the backend.

// =================================================================================================
// Getting started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

The `finish` directory contains the finished JWT security implementation for the
services in the application. You can try the finished application before you
build your own.

To try out the application, first navigate to the `finish` directory.

Run the following Maven goal from the `frontend` directory to build the application and deploy it to Open Liberty:

[role='command']
```
mvn liberty:run
```

Open another command-line session, navigate to the `system` directory and run the following Maven goal:

[role='command']
```
mvn liberty:run
```

After you see the following message in both command-line sessions, both of your services are ready:

[source, role="no_copy"]
----
The defaultServer server is ready to run a smarter planet.
----

Navigate your browser to the frontend web application endpoint:
http://localhost:9090/login.jsf[http://localhost:9090/login.jsf^]. From here,
you can log in to the application with the form-based login.

Log in with one of the following user information credentials:

|===
| *Username* | *Password* | *Role*
| bob | bobpwd | admin, user
| alice | alicepwd | user
| carl | carlpwd | user
|===

You will be redirected to a page that displays some information that the
frontend has requested from the `system` service, such as the system username.
If you log in as an `admin` user, the current OS will also be shown. If you log in as
a `user`, you will instead see the message `You are not authorized to access
this system property`, as the `user` role does not have sufficient privileges.

Additionally, the `groups` claim of the JWT is read by the system service and
requested by the frontend to be displayed.

You can try accessing these services without a JWT by entering the system endpoint 
https://localhost:8443/system/properties/os[https://localhost:8443/system/properties/os]
directly into your browser. You can see that you are not able to access it
because you didn't supply a valid JWT with the request. The following error
will appear in the command-line session of the `system` service:

[source, role="no_copy"]
----
[ERROR] CWWKS5522E: The MicroProfile JWT feature cannot perform authentication because a MicroProfile JWT cannot be found in the request.
----

When you are done with the application, stop both the `frontend` and `system`
services by pressing CTRL+C in the command-line sessions where you ran them.
Alternatively, you can run the following goals from the `finish` directory in
another command-line session:

[role='command']
```
mvn -pl system liberty:stop
mvn -pl frontend liberty:stop
```

// =================================================================================================
// Configuring MicroProfile JWT
// =================================================================================================

== Configuring MicroProfile JWT

// File 0
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/main/liberty/config/server.xml[]
----

// File 1
microprofile-config.properties
[source, text, linenums, role="code_column hide_tags=propagateHeaders"]
----
include::finish/system/src/main/webapp/META-INF/microprofile-config.properties[]
----

Navigate to the `start` directory to begin.

When you run Open Liberty in dev mode, the server listens for file changes and
automatically recompiles and deploys your updates whenever you save a new
change. Navigate to the `frontend` directory and run the following goal to start the
`frontend` service in dev mode:

[role='command']
```
mvn liberty:dev
```

Open another command-line session, navigate to the `system` directory
and run the following goal to start the `system` service in dev mode:

[role='command']
```
mvn liberty:dev
```

After you see the following message, your application server in dev mode is ready:

[source, role="no_copy"]
----
Press the Enter key to run tests on demand.
----

Add the MicroProfile JWT feature to the server configuration file for
the `system` service. 

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the system server configuration file.#
`system/src/main/liberty/config/server.xml`
----

The [hotspot=mpJwt file=0]`mpJwt` feature adds the libraries that are required for MicroProfile JWT implementation.

Next, configure the `mpJwt` feature in the `microprofile-config.properties` file for the `system` service.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the microprofile-config.properties file.#
`system/src/main/webapp/META-INF/microprofile-config.properties`
----

The [hotspot=issuer file=1]`mp.jwt.verify.issuer` config property specifies what the expected value of
the `iss` (issuer) claim is on an incoming JWT. Incoming JWTs with an issuer
claim different from this expected value are not considered valid.

// =================================================================================================
// Creating secure system service
// =================================================================================================

== Creating secure system service

Create a secure service that provides system properties to the frontend.

// File 0
SystemResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemResource` class.#
`system/src/main/java/io/openliberty/guides/system/SystemResource.java`
----

This class has role-based access control. The role names that are used in the
[hotspot=rolesAllowedAdminUser1 hotspot=rolesAllowedAdminUser2
hotspot=rolesAllowedAdmin file=0]`@RolesAllowed` annotations are mapped to group
names in the `groups` claim of the JWT, which results in an authorization
decision wherever the security constraint is applied.

The [hotspot=usernameEndpoint file=0]`/username` endpoint returns the system's username and is annoted with the
[hotspot=rolesAllowedAdminUser1 file=0]`@RolesAllowed({"admin, "user"})`
annotation. Only authenticated users with the role of `admin` or `user` to
can access this endpoint.

The [hotspot=osEndpoint file=0]`/os` endpoint returns the system's current OS. The
[hotspot=rolesAllowedAdmin file=0]`@RolesAllowed` annotation is limited to
`admin`, meaning only authenticated users with the role of `admin` are able to
access the endpoint.

While the [hotspot=rolesAllowedAdminUser1 hotspot=rolesAllowedAdminUser2
hotspot=rolesAllowedAdmin file=0]`@RolesAllowed` annotation automatically reads from the `groups` claim
of the JWT to make an authorization decision, you can also manually access the
claims of the JWT using the [hotspot=claim file=0]`@Claim` annotation. In this
case, the `groups` claim is injected into the [hotspot=rolesArray
file=0]`roles` JSON array. The roles parsed from the `groups` claim of the
JWT are then exposed back to the frontend at the [hotspot=rolesEndpoint
file=0]`/jwtRoles` endpoint. To read more about different claims and ways to
access them, check out the
https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/interoperability.asciidoc[MP-JWT
documentation^].

// =================================================================================================
// Creating a client to access the secure system service
// =================================================================================================

== Creating a client to access the secure system service

// File 0
SystemClient.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/frontend/src/main/java/io/openliberty/guides/frontend/client/SystemClient.java[]
----

// File 1
ApplicationBean.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/frontend/src/main/java/io/openliberty/guides/frontend/ApplicationBean.java[]
----

// File 2
LoginBean.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/frontend/src/main/java/io/openliberty/guides/frontend/LoginBean.java[]
----

Create a RESTful client interface for the `system` service. 

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemClient` class.#
`frontend/src/main/java/io/openliberty/guides/frontend/client/SystemClient.java`
----

This interface declares methods for accessing each of the endpoints previously
set up in the `system` service. 

The MicroProfile Rest Client feature automatically builds and generates a client
implementation based on what is defined in the [hotspot=systemClient file=0]`SystemClient` interface. There is
no need to set up the client and connect with the remote service.

As discussed, the `system` service is secured and requests made to it must
include a valid JWT in the `Authorization` header. The [hotspot=headerParam1
hotspot=headerParam2 hotspot=headerParam3 file=0]`@HeaderParam` annotation is
used to specify that the value of the `String authorization` parameter of these
methods is used as the `Authorization` header of requests made to the `system`
service through this client. The JWT will be passed into these methods by the
application bean, which you will create now.

Create the application bean that the frontend UI uses to request data.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `ApplicationBean` class.#
`frontend/src/main/java/io/openliberty/guides/frontend/ApplicationBean.java`
----

The application bean provides the methods used by the web app to populate the
table in the UI. The web app code has already been given to you. The methods
[hotspot=getOs file=1]`getOs()`, [hotspot=getUsername file=1]`getUsername()`,
and [hotspot=getJwtRoles file=1]`getJwtRoles()` each call thier associated
method of [hotspot=restClient file=1]`defaultRestClient`, an injected instance
of the [hotspot=systemClient file=0]`SystemClient` class you created. Each of
these methods make a request to the `system` service for data. Passed in as a
paramter to these [hotspot=restClient file=1]`defaultRestClient` methods is
[hotspot=authHeader1 hotspot=authHeader2 hotspot=authHeader3
file=1]`authHeader`, or the authentication header, which is the JWT with
`Bearer` prepended to it. As explained above, when the [hotspot=authHeader1
hotspot=authHeader2 hotspot=authHeader3 file=1]`authHeader` is passed into the
[hotspot=systemClient file=0]`SystemClient` methods, the [hotspot=headerParam1
hotspot=headerParam2 hotspot=headerParam3 file=0]`@HeaderParam` annotation will
add it to the `Authorization` header of the associated requests made to the
`system` service.

The JWT for these requests is retreived from the session attributes using the
[hotspot=getJwt file=1]`getJwt()` method. The JWT is stored in the session
attributed by the provided [hotspot=loginBean file=2]`LoginBean` class. When the
user logs into the frontend, the [hotspot=doLogin file=2]`doLogin()` method is
called which builds the JWT and [hotspot=setAttribute file=2]`setAttribute()`
stores it as an `HttpSession` attribute. The JWT is built by the
[hotspot=buildJwt file=2]`buildJwt()` method which uses the [hotspot=jwtBuilder
file=2]`JwtBuilder` class included in the [hotspot=securityJwt
file=2]`com.ibm.websphere.security.jwt` package. You can see that the
[hotspot=groups file=2]`claim()` method is being used to set the `groups` claim
of the token. This is the claim that is used to provide the role based access
that you have implemented. 



// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

Because you are running the `frontend` and `system` services in `dev` mode, the changes you made have been automatically picked up. You can now checkout your application in the browser.

Navigate your browser to the front end web application endpoint: http://localhost:9090/login.jsf. Use one of the following credentials to log in:

|===
| *Username* | *Password* | *Role*
| bob | bobpwd | admin, user
| alice | alicepwd | user
| carl | carlpwd | user
|===

Once you log in, you can see the information retrieved from the `system`
service. If you successfully implemented role-based access, you can see that if
you log in as a `user` role without `admin`, you won't have access to the
OS. 

You can also see the value of the `groups` claim in the row labeled `Roles:`.
These are being read from the JWT and sent back to the frontend to
be displayed.

You can check that the `system` service is secured against unauthenticated
requests by entering the system endpoint
https://localhost:8443/system/properties/os[https://localhost:8443/system/properties/os]
directly into your browser. 

In the frontend you should see your JWT displayed in the bottom row labeled `JSON Web Token`.

To see the specific information that this JWT holds, you can enter it into the https://JWT.io[JWT.io website^], which includes a token reader.

You can see the header, which contains information about the JWT:

[source, role="no_copy"]
----
{
  "kid": "NPzyG3ZMzljUwQgbzi44",
  "typ": "JWT",
  "alg": "RS256"
}
----

And you can see the payload which contains the claims:

[source, role="no_copy"]
----
{
  "token_type": "Bearer",
  "sub": "bob",
  "upn": "bob",
  "groups": [ "admin", "user" ],
  "iss": "http://openliberty.io",
  "exp": 1596723489,
  "iat": 1596637089
}
----

You can read more about these of these claims in the https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/interoperability.asciidoc[MP-JWT documentation^]

// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

// File 0
SystemEndpointIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java[]
----

You can manually check that the system service is secure by making requests to
each of the endpoints with and without valid JWTs, however automated tests are a
much better approach since they are more reliable and trigger a failure if a
change introduces a defect.  

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemEndpointIT` class.#
`system/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java`
----

The tests `testOSEndpoint()`[hotspot=os file=0],
`testUsernameEndpoint()`[hotspot=username file=0], and
`testRolesEndpoint()`[hotspot=roles file=0] test the `/os`, `/username`, and
`/roles` endpoints, respectively.


Each test makes 3 requests to its associated endpoint: one with a JWT with the
`admin`[hotspot=adminRequest1 hotspot=adminRequest2 hotspot=adminRequest3
file=0] role, one with a JWT with the just the `user`[hotspot=userRequest1
hotspot=userRequest2 hotspot=userRequest3 file=0] role, and a third with `no
JWT`[hotspot=nojwtRequest1 hotspot=nojwtRequest1 hotspot=nojwtRequest1 file=0]
at all. The responses of these requests are checked for correctness based on the
role-based access rules for that endpoint. The `admin` requests should be
successful on all endpoints, the `user` requests should be denied by `/os`
endpoint but go through on the `/username` and `/jwtroles`, and the requests
that don't have a JWT should be denied access to all endpoints.

=== Running the tests

Since you started Open Liberty in dev mode, press the enter/return key from the
`system` directory to run the tests. You will see the following output:

[source, role="no_copy"]
----
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running it.io.openliberty.guides.system.SystemEndpointIT
[INFO] [ERROR   ] CWWKS5522E: The MicroProfile JWT feature cannot perform authentication because a MicroProfile JWT cannot be found in the request.
[INFO] [ERROR   ] CWWKS5522E: The MicroProfile JWT feature cannot perform authentication because a MicroProfile JWT cannot be found in the request.
[INFO] [ERROR   ] CWWKS5522E: The MicroProfile JWT feature cannot perform authentication because a MicroProfile JWT cannot be found in the request.
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.648 s - in it.io.openliberty.guides.system.SystemEndpointIT
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

When you are finished testing the application, stop both the `frontend` and `system`
services by pressing CTRL+C in the command-line sessions where you ran them.
Alternatively, you can run the following goals from the `start` directory in
another command-line session:

[role='command']
```
mvn -pl system liberty:stop
mvn -pl frontend liberty:stop
```

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You learned how to use MicroProfile JWT to validate JWTs and authorize users to secure your microservices in Open Liberty.

Next, you can try one of the related MicroProfile guides. They demonstrate technologies that you can learn and expand on what you built here.



include::{common-includes}/attribution.adoc[subs="attributes"]
