// Copyright (c) 2018, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-jwt
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2018-03-09
:page-guide-category: microprofile
:page-essential: false
:page-description: Learn how to control user and role access to microservices using MicroProfile JWT.
:page-tags: ["MicroProfile", "Security"]
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Securing Java microservices with Eclipse MicroProfile JSON Web Token (MicroProfile JWT)
:page-seo-description: A getting started tutorial and an example on how to secure Java microservices to authenticate users and authorize access by validating JSON Web Tokens (JWT) using Eclipse MicroProfile JWT.
:guide-author: Open Liberty
= Securing microservices with JSON Web Tokens

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

You'll explore how to control user and role access to microservices with MicroProfile JSON Web Token (MicroProfile JWT).

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You will add MicroProfile JWT to validate security tokens in the `system` and
`inventory` microservices. You will use a token-based authentication mechanism
to authenticate, authorize, and verify user identities based on a security
token.

For microservices, a token-based authentication mechanism offers a lightweight
way for security controls and security tokens to propagate user identities
across different services. JSON Web Token (JWT) is becoming the most common
token format because it follows well-defined and known standards.

MicroProfile JWT standards define the required format of JWT for authentication
and authorization. The standards also map JWT token claims to various Java EE
container APIs and make the set of claims available through getters.

The application that you will be working with is an `inventory` service, which
stores the information about various JVMs that run on different systems.
Whenever a request is made to the `inventory` service to retrieve the JVM system
properties of a particular host, the `inventory` service communicates with the
`system` service on that host to get these system properties. The JWT token gets
propagated and verified during the communication between two services.

// =================================================================================================
//  JSON Web Tokens
// =================================================================================================

== JSON Web Tokens for Authorization and Authentication

=== What is a JSON Web Token

A JSON Web Token is a self contained token designed to securely transmit information as a JSON object.
The information in this JSON object is digitally signed and can be trusted and verified by the recipient. 

A JWT contains 3 different parts, a header, a payload, and a signature, with each
part being seperated by a dot (`.`). An encoded token takes the following form:

`xxxxx.yyyyy.zzzzz`

The header contains the type of token, and the signing algorithm used.

The payload contains the claims of a token. The claims are statements about the
user and other information. Some examples of claims are `iss` (issuer), `exp`
(expiration time), and `upn` (unique principal name, or just name). Custom claims can be added to the token to include any other
information you would like to transmit.

The signature is used to verify that the message wasn't changed along the way, and
can verify that the sender of the JWT is who it says it is.

=== JSON Web Tokens for Authorization and Authentication

In our case, we will be using JWTs to authenticate a user, allowing them to make
authorized requests to backend services. 

The user will sign into the frontend application using a username and password,
at which point a JWT will be created by the frontend and signed using a private
key. The frontend will then make requests to the backend services with the JWT
included in the `Authorization` header of the request. The backend services,
which are secured, will examine the JWT included with the request and use the
frontends public key to verify the signature of the JWT to ensure that the
request did in fact come from the authorized frontend. After a JWT has been
validated, the information in the claims of the JWT, such as the user's
role, can be trusted and will be used to determine which services the requesting
user has access to in the backend.


// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Try what you'll build
// =================================================================================================

== Try what you'll build

The `finish` directory contains the finished JWT security implementation for the
services in the application. You can try the finished application before you
build your own.

To try out the application, first navigate to the `finish` directory.

Execute the following command from the `frontend` directory to run a script that
starts the frontend module in the background.

[role='command']
```
./startFrontend.sh
```

Next, navigate out of the `frontend` directory and into the `inventory` directory and run the following goal:

[role='command']
```
mvn liberty:run
```

In a new tab of your command-line session, navigate to the `system` directory and run the following goal:

[role='command']
```
mvn liberty:run
```

Navigate your browser to the front end web application endpoint:
http://localhost:9090/login.jsf[http://localhost:9090/login.jsf^]. From here,
you can log in to the application with the form-based login.

Log in with one of the following user information credentials:

|===
| *Username* | *Password* | *Role*
| bob | bobpwd | admin, user
| alice | alicepwd | user
| carl | carlpwd | user
|===

You will be redirected to a page that displays some information. The current OS is
requsted from the `system` service, and the inventory size is requested from the
`inventory` service. Both of these services are secured and require a valid JWT
to be in the request's header. If you log in as an `admin` user, the current inventory size
appears and can add systems to this inventory using the interface beneath the bottom row. If you
log in as a `user`, you will instead see the message, `You are not authorized to
access the inventory service`, as the role does not have sufficient privileges. 

Additionally, the `name` and `groups` claim of the JWT are read by the inventory
service and are exposed to the frontend to be displayed.

You can try accessing these services without a JWT by entering the inventory URL,
https://localhost:9443/inventory/systems[https://localhost:9443/inventory/systems],
or the system URL,
https://localhost:8443/system/properties[https://localhost:8443/system/properties]
directly into your browser. You can see that you are not able to access them
because you didn't supply a valid JWT with the request. The following error
will appear in the command-line sessions of the services you tried to
access:

[source, role="no_copy"]
----
[ERROR] CWWKS5522E: The MicroProfile JWT feature cannot perform authentication because a MicroProfile JWT cannot be found in the request.
----

When you are done with the application, stop both the `inventory` and `system`
services  by pressing CTRL+C in the command-line session where you ran them.
Afterward, run the `liberty:stop` goal from the `frontend` directory.

[role='command']
```
mvn liberty:stop
```

// =================================================================================================
// Configuring MicroProfile JWT
// =================================================================================================

== Configuring MicroProfile JWT

// File 0
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/liberty/config/server.xml[]
----

// File 1
microprofile-config.properties
[source, text, linenums, role="code_column hide_tags=propagateHeaders"]
----
include::finish/inventory/src/main/webapp/META-INF/microprofile-config.properties[]
----

Navigate to the `start` directory.

Execute the following command from the `frontend` directory to
run a script that starts the frontend module in the background.

[role='command']
```
./startFrontend.sh
```

Next, navigate out of the `frontend` directory and into the `inventory`
directory and run the following goal to start the `inventory` service in `dev` mode:

[role='command']
```
mvn liberty:dev
```

In a new tab of your command-line session, navigate to the `system` directory and run the
following goal to start the `system` service in `dev` mode:

[role='command']
```
mvn liberty:dev
```

When you run Open Liberty in `dev` mode, the server listens for file changes and
automatically recompiles and deploys your updates whenever you save a new
change.

First add the MicroProfile JWT feature to the server configuration file for
the `inventory` service. 

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the inventory server configuration file.#
`inventory/src/main/liberty/config/server.xml`
----

This has already been done for you in the `system` service.

The [hotspot=mpJwt file=0]`mpJwt` feature adds the libraries that are required for MicroProfile JWT implementation.


Next, configure the `mpJwt` feature in the `microprofile-config.properties` file for the `inventory` service.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the microprofile-config.properties file.#
`inventory/src/main/webapp/META-INF/microprofile-config.properties`
----

This has already been done for you in the `system` service.

The [hotspot=issuer file=1]`mp.jwt.verify.issuer` config property specifies what the expected value of
the `iss` (issuer) claim is on an incoming JWT. Incoming JWTs with an issuer
claim different from this expected value are not considered valid.

The [hotspot=location file=1]`mp.jwt.verify.publickey.location` config properties specifies the location
of the public key to be used to validate the an incoming JWT's signature. In
this case, the `frontend` service, where our JWT is built, provides an endpoint
to retrieve the public signing key.


// =================================================================================================
// Creating secure system and inventory services
// =================================================================================================

== Creating secure system and inventory services

// File 0
SystemResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/main/java/io/openliberty/guides/system/SystemResource.java[]
----

// File 1
InventoryResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

// File 2
SystemClient.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[]
----

// File 3
microprofile-config.properties
[source, text, linenums, role="code_column"]
----
include::finish/inventory/src/main/webapp/META-INF/microprofile-config.properties[]
----

Create the `SystemResource` class.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemResource` class.#
`system/src/main/java/io/openliberty/guides/system/SystemResource.java`
----

This class has role-based access control. The role names that are used in the
[hotspot=rolesAllowed file=0]`@RolesAllowed` annotation are mapped to group names in
the `groups` claim of the JWT, which results in an authorization decision
wherever the security constraint is applied.

The [hotspot=rolesAllowed file=0]`@RolesAllowed({"admin, "user"})` annotation allows only authenticated users with the role of `admin` or `user` to access the `system` service.
Therefore, this service is properly secured.

Next, create the `InventoryResource` class.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `InventoryResource` class.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
----

In this class, the [hotspot=rolesAllowed file=1]`@RolesAllowed` annotation is limited to `admin` meaning only authenticated users with the role of `admin` are able to access the `inventory` service

Create a RESTful client interface for the `system` service. 

[role="code_command hotspot file=2", subs="quotes"]
----
#Create the `SystemClient` class.#
`inventory/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java`
----

The MicroProfile Rest Client feature automatically builds and generates a client
implementation based on what is defined in the `SystemClient` interface. There is
no need to set up the client and connect with the remote service.

As stated previously, when the `inventory` service requests properties from the
`system` service, there must be a valid JWT included in the request.

The [hotspot=registerClientHeaders file=2]`@RegisterClientHeaders` annotation instructs the client to propagate the
headers specified in the MicroProfile Config property
[hotspot=propagateHeaders file=3]`org.eclipse.microprofile.rest.client.propagateHeaders`.

In the case, the `inventory` received a request with a JWT in the
`Authorization` header, so you must propagate that header to the `system`
service.

Add the [hotspot=propagateHeaders file=3]`org.eclipse.microprofile.rest.client.propagateHeaders` MicroProfile
Config property for the inventory service and specify the `Authorization` header.

[role="code_command hotspot file=3", subs="quotes"]
----
#Replace the microprofile-config.properties file.#
`inventory/src/main/webapp/META-INF/microprofile-config.properties`
----

The `inventory` service will now propagate the `Authorization` header, which contains the JWT, to the `system` service. 


// =================================================================================================
// Manually accessing JWT claims
// =================================================================================================

== Manually accessing JWT claims

// File 0
JwtResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/JwtResource.java[]
----

The previous section showed how to implement role-based access control with the
`@RolesAllowed` annotation, which automatically reads from the `groups` claim of
the JWT and makes an authorization decision.

If you wish to manually access the claims of the JWT, perhaps to provide more
granual access control, MicroProfile JWT provides you with "get style" accessors.

Create a new service that uses these accessors to read the `upn` (unique principal name, or user name) and `groups`
claim of the incoming JWT. Show that this information was able to be retrived
by exposing endpoints that provide this information back to the frontend. 

[role="code_command hotspot", subs="quotes"]
----
#Create the `JwtResource` class.#
`inventory/src/main/java/io/openliberty/guides/inventory/JwtResource.java`
----

JwtResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/JwtResource.java[]
----

In this case you are using the [hotspot=getName file=0]`getName()` and [hotspot=getGroups file=0]`getGroups()` accessors of the
[hotspot=jsonWebToken file=0]`org.eclipse.microprofile.jwt.JsonWebToken` class. To see a full list of
accessors for different claims, including how to access custom claims, check out the https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/interoperability.asciidoc[MP-JWT documentation^]

// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

Because you are running the `system` and `inventory` in `dev` mode, the changes you made have been automatically picked up. You can now checkout your application in the browser.

Navigate your browser to the front end web application endpoint: http://localhost:9090/login.jsf. Use one of the following credentials to log in:

|===
| *Username* | *Password* | *Role*
| bob | bobpwd | admin, user
| alice | alicepwd | user
| carl | carlpwd | user
|===

Once you log in, you can see some information retrieved from the backend
services. If you successfully implemented role-based access, you can see that if
you log in as a `user` role without `admin`, you won't have access to the
inventory size. 

You can also see the values of the `name` and `groups` claims in the top two
rows. Again, these are being read from the JWT and sent back to the frontend to
be displayed.

You can check that the backend systems are secured against unauthenticated
requests by entering inventory URL,
https://localhost:9443/inventory/systems[https://localhost:9443/inventory/systems],
or the system URL,
https://localhost:8443/system/properties[https://localhost:8443/system/properties].

In the frontend you should see your JWT displayed in the bottom row labeled `JSON Web Token`.

To see the specific information that this JWT holds, you can enter it into the https://JWT.io[JWT.io website^], which includes a token reader.

You can see the header, which contains information about the JWT:

[source, role="no_copy"]
----
{
  "kid": "NPzyG3ZMzljUwQgbzi44",
  "typ": "JWT",
  "alg": "RS256"
}
----

And you can see the payload which contains the claims:

[source, role="no_copy"]
----
{
  "token_type": "Bearer",
  "sub": "bob",
  "upn": "bob",
  "groups": [ "admin", "user" ],
  "iss": "http://openliberty.io",
  "exp": 1596723489,
  "iat": 1596637089
}
----

You can read more about the specific of these claims in the https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/interoperability.asciidoc[MP-JWT documentation^]

// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

To-do

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You learned how to use MicroProfile JWT to validate JWTs and authorize users to secure your microservices in Open Liberty.

Next, you can try one of the related MicroProfile guides. They demonstrate technologies that you can learn and expand on what you built here.



include::{common-includes}/attribution.adoc[subs="attributes"]
